import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../models/finance_models.dart';
import '../../services/booking_service.dart';
import '../../services/route_service.dart';
import '../../utils/app_theme.dart';
import '../../utils/squircle_container.dart';

class TripTransportSection extends StatelessWidget {
  final TripPlan trip;
  final bool isDark;
  final Future<void> Function(TripPlan updated) onChanged;

  const TripTransportSection({
    super.key,
    required this.trip,
    required this.isDark,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    final surfaceColor = isDark ? AppColors.darkSurface : AppColors.lightSurface;
    final shadowColor = isDark ? AppColors.darkCardShadow : AppColors.lightCardShadow;

    final allTransports = [...trip.transports];
    final missingRoutes = RouteService.generateMissingRoutes(trip);
    allTransports.addAll(missingRoutes);
    allTransports.sort((a, b) => a.departureDate.compareTo(b.departureDate));

    if (allTransports.isEmpty) return const SizedBox.shrink();

    final totalCost = allTransports.fold<int>(0, (sum, t) => sum + t.estimatedCostCents);

    return SquircleContainer(
      borderRadius: BorderRadius.circular(24),
      padding: const EdgeInsets.all(20),
      backgroundColor: surfaceColor,
      boxShadow: [BoxShadow(color: shadowColor, blurRadius: 18, offset: const Offset(0, 7))],
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          const Icon(Icons.train_rounded, color: AppColors.primary, size: 20),
          const SizedBox(width: 8),
          Expanded(child: Text('Verbindungen', style: Theme.of(context).textTheme.titleMedium)),
          Text(_money(totalCost), style: const TextStyle(fontWeight: FontWeight.w800, color: AppColors.primary)),
        ]),
        const SizedBox(height: 14),
        ...allTransports.map((t) => _transportTile(context, t, missingRoutes.any((m) => m.id == t.id))),
      ]),
    );
  }

  Widget _transportTile(BuildContext context, TripTransport t, bool isAutoGenerated) {
    final mutedColor = isDark ? AppColors.darkMuted : AppColors.lightMuted;
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkSurface2 : const Color(0xFFF8F9FC),
        borderRadius: BorderRadius.circular(14),
        border: isAutoGenerated ? Border.all(color: AppColors.amber.withValues(alpha: .3), width: 1) : null,
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Container(
            width: 34,
            height: 34,
            decoration: BoxDecoration(
              color: t.mode.color.withValues(alpha: .11),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(t.mode.icon, size: 18, color: t.mode.color),
          ),
          const SizedBox(width: 10),
          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('${t.fromLocation} → ${t.toLocation}', style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13)),
            Row(children: [
              Text(t.mode.label, style: TextStyle(fontSize: 11, color: t.mode.color, fontWeight: FontWeight.w600)),
              if (t.durationMinutes != null) ...[
                Text(' · ', style: TextStyle(fontSize: 11, color: mutedColor)),
                Text(RouteService.formatDuration(t.durationMinutes!), style: TextStyle(fontSize: 11, color: mutedColor)),
              ],
              if (isAutoGenerated) ...[
                const SizedBox(width: 6),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 1),
                  decoration: BoxDecoration(color: AppColors.amber.withValues(alpha: .12), borderRadius: BorderRadius.circular(6)),
                  child: const Text('Auto', style: TextStyle(fontSize: 9, fontWeight: FontWeight.w600, color: AppColors.amber)),
                ),
              ],
            ]),
          ])),
          Text(_money(t.estimatedCostCents), style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 14)),
          if (t.isBooked) ...[
            const SizedBox(width: 6),
            const Icon(Icons.check_circle_rounded, size: 16, color: AppColors.green),
          ],
        ]),
        const SizedBox(height: 8),
        Row(children: [
          _bookingChip(context, 'Google Maps', Icons.map_outlined, AppColors.green, () {
            launchUrl(Uri.parse(BookingService.getGoogleMapsLink(t.fromLocation, t.toLocation)));
          }),
          const SizedBox(width: 6),
          _bookingChip(context, 'DB', Icons.train_rounded, AppColors.primary, () {
            final links = BookingService.getLinks(transport: t);
            launchUrl(Uri.parse(links.dbUrl!));
          }),
          const SizedBox(width: 6),
          _bookingChip(context, 'Omio', Icons.directions_bus_rounded, AppColors.amber, () {
            final links = BookingService.getLinks(transport: t);
            launchUrl(Uri.parse(links.omioUrl!));
          }),
        ]),
      ]),
    );
  }

  Widget _bookingChip(BuildContext context, String label, IconData icon, Color color, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(8),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
        decoration: BoxDecoration(
          color: color.withValues(alpha: .08),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Icon(icon, size: 13, color: color),
          const SizedBox(width: 4),
          Text(label, style: TextStyle(fontSize: 10, fontWeight: FontWeight.w600, color: color)),
        ]),
      ),
    );
  }

  String _money(int cents) => '${(cents / 100).toStringAsFixed(0)} €';
}
